// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdfEh1Qua7df544graWlQl3cQa8OHOcg0',
    appId: '1:849027164026:web:425d283e617207e778d8c3',
    messagingSenderId: '849027164026',
    projectId: 'flipkart-clone-85608',
    authDomain: 'flipkart-clone-85608.firebaseapp.com',
    storageBucket: 'flipkart-clone-85608.firebasestorage.app',
    measurementId: 'G-L26F9FZ1B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMFpVhA-cQ9VE5fHXATbyaNgJklmiBOJQ',
    appId: '1:849027164026:android:156f9680fa204f8778d8c3',
    messagingSenderId: '849027164026',
    projectId: 'flipkart-clone-85608',
    storageBucket: 'flipkart-clone-85608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB89QR1D_DuF48f3xob9F8OWWjLoZLmDnI',
    appId: '1:849027164026:ios:8007e4a7eb4f141e78d8c3',
    messagingSenderId: '849027164026',
    projectId: 'flipkart-clone-85608',
    storageBucket: 'flipkart-clone-85608.firebasestorage.app',
    androidClientId: '849027164026-8b1gl5ofvg10ms4bf3bhci33ivg0omu3.apps.googleusercontent.com',
    iosClientId: '849027164026-4cj45hu453mh9db851k681ljvluune78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flipkartClone',
  );
}
